name: Install Dependencies

on:
  push:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Navigate to web folder
        run: cd web

      - name: Install dependencies
        run: pnpm install
